### ISSUE TITLE
pacote não instalando com o guzzle na versão 7

### ISSUE THREAD

**Issue by BreakinAnt** [melhorenvio/shipment-sdk-php#15]
melhorenvio/shipment-sdk-php 2.0.0 requires guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1)

**Comment by viniciustessmann** [comment]
Olá, 
Esse problema foi resolvido na última versão do pacote.
Obrigado por nos notificar sobre.
