### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by buscacomponentes** [melhorenvio/shipment-sdk-php#8]
Recebi esta msg ao tentar instalar no Ubuntu Ubuntu 20.04.2 LTS

$ composer require melhorenvio/shipment-sdk-php
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2

In InitCommand.php line 756:
                                                                                                                     
  Package melhorenvio/shipment-sdk-php at version  has a PHP requirement incompatible with your PHP version (7.4.3)

**Comment by gabrielrbarbosa** [comment]
#9

**Comment by viniciustessmann** [comment]
Olá @gabrielrbarbosa e @buscacomponentes 
Esse problema foi resolvido na última versão do pacote.
Obrigado pela abertura da issue.
